### ISSUE TITLE
Printer can be enabled and used on wilderness and not owned territories

### ISSUE THREAD

**Issue by Alexre** [bsalha1/Printer#1]
I can enable printer mode in enemy territories and wilderness even though the options are set to:

factions:
  support: true
  allow-in-wilderness: false

I'm using SaberFactions 2.4.0-RC

**Comment by Alexre** [comment]
After a server restart, this issue happens, but If I reload printer with plugman, the region restriction seems to work fine, maybe a priority issue?

**Comment by bsalha1** [comment]
Working on fixing this right now - it is a priority issue. I will keep you posted.

**Comment by bsalha1** [comment]
After a few days of testing I've found that the issue is impossible to fix as I cannot control how Factions plugins initialize and I cannot automate the fix. What you have to do is go into the plugin.yml in the Printer.jar file (with a program like Win-RAR) and put Factions next to Vault in the depends list Ex: depends: [Vault, Factions]
